name: check
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - run: ./build.sh
      - run: python3 -m unittest discover -s tests -v
